### ISSUE TITLE
Feature Facade is not working.

### ISSUE THREAD

**Issue by shubhamdexbytes** [francescomalatesta/laravel-feature#10]
I have added the following line my app.php under alias array 
**'Feature' => \LaravelFeature\Facade\Feature::class,**
and added following code to my controller 
   **Feature::add('auto_dispatch', false);**

but it says me - **FatalErrorException in FeaturesUIController.php line 20:
Class 'App\Http\Controllers\Feature' not found**

**Comment by francescomalatesta** [comment]
Sorry for the late, I wasn't around for a while :(

However, it seems that you forgot the `use Feature;` instruction right after the namespace definition.

Just tried it and it works, without it I have the same error you had.
