### ISSUE TITLE
Is there a way to disable migrations

### ISSUE THREAD

**Issue by catalinux** [francescomalatesta/laravel-feature#11]
## Detailed description

I need a way to disable  the migrations that are run automatically when I run `php artisan migrate`

## Context

You might need that when you need a different repository (features might be hardcodedd or kept in a different database than the default one)

## Possible implementation

a config key that default would be enabled

## Your environment

Any environment

**Comment by francescomalatesta** [comment]
Sorry for the late, I wasn't around for a while :(

For future record:

* If you don't need migrations you can just remove them before executing, right now by default the package works with them;
* about different repositories, take a look at https://github.com/francescomalatesta/laravel-feature#using-a-custom-features-repository;
