### ISSUE TITLE
Correct Namespace to use on a User model with Featurable?

### ISSUE THREAD

**Issue by jasondavis** [francescomalatesta/laravel-feature#2]
I am trying to use this library like the example in the `README.md` file shows in my User model.  I get this error:

    FatalErrorException in User.php line 29:
    Trait 'LaravelFeature\Featurable' not found

---

**User.php Model**

    <?php
    namespace App\Models;

    use App\Models\User;
    use OwenIt\Auditing\Auditable;
    use Laravel\Passport\HasApiTokens;
    use Illuminate\Notifications\Notifiable;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    use Mpociot\Teamwork\Traits\UserHasTeams;
    use Skybluesofa\Followers\Traits\Followable;
    use LaravelFeature\Domain;
    use LaravelFeature\Featurable\FeaturableInterface;
    use LaravelFeature\Featurable;
    use LaravelFeature;

    class User extends Authenticatable implements FeaturableInterface
    {
        use HasApiTokens, Notifiable, Auditable, UserHasTeams, Followable, Featurable;
    }

---

I have tried adding many different `use` combinations at the top of the file for the namespace but with no luck.  Can someone please post the correct namespace usage?

**Comment by jasondavis** [comment]
Finally I got it!
Please add to the README.md!

    use LaravelFeature\Featurable\Featurable;

**Comment by francescomalatesta** [comment]
Closing this as I have already specified it [here](https://github.com/francescomalatesta/laravel-feature#enable-features-management-for-specific-users).
