### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by n00el** [francescomalatesta/laravel-feature#3]
Hi.

It's working on laravel 5.4? 
Because I try to install this fantastic package to my laravel, composer have it, but when I use php artisan migrate, nothing happens.

Composer require laravel-feature, but require "francescomalatesta/laravel-feature": "^0.1.0", but nothing happens then.

Please make it workable, I love this package! 👍  🥇

**Comment by Treggats** [comment]
Works on Laravel 5.5 did you register the service provider?

**Comment by francescomalatesta** [comment]
It works also on 5.6 :) closing
