### ISSUE TITLE
Where to add the Feature::add()

### ISSUE THREAD

**Issue by ppounder** [francescomalatesta/laravel-feature#5]
Apologies, this isn't particularly an issue, possibly more of a documentation update/clarification.

On the [declare a new feature](https://github.com/francescomalatesta/laravel-feature#declare-a-new-feature) section of the documentation:
```
Declare a New Feature

Let's say you have a new feature that you want to keep hidden until a certain moment. We will call it "page_code_cleaner". Let's add it to our application:
````

Can you advise where you would advise is the best place in your application to add you ```Feature:add```'s? We originally added this into the boot() of the AppServiceProvider, but this ultimately updates the DB every request? Where is the best place to put this as you really only want to call this once, or would you recommend just adding a database seed to add it?

Kind regards

Paul Pounder

**Comment by n00el** [comment]
Create an artisan command for this, I thing.

**Comment by francescomalatesta** [comment]
You must declare a new feature when you need it (maybe in a fixture file, or a controller action, it depends by your necessity).
